name: CI

on: [push, pull_request]

env:
  CI: true
  PGUSER: postgres
  PGPASSWORD: postgres
  PGHOST: "127.0.0.1"
  PGPORT: 5432
  TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

jobs:
  test:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 14.x]
        postgres-version: [9.4, 10, 11, 12]

    services:
      postgres:
        image: postgres:${{ matrix.postgres-version }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - "0.0.0.0:5432:5432"
        # needed because the postgres container does not provide a healthcheck
        options:
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn --frozen-lockfile
      - run: scripts/test
        env:
          PGVERSION: ${{ matrix.postgres-version }}
