name: Publish

on:
  release:
    types: [published]

concurrency:
  group: "publish"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Node version
        run: echo "NODE_VERSION=$(cat .nvmrc)" > $GITHUB_ENV
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - run: npm install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}